### ISSUE TITLE
Refactor Tracking

### ISSUE THREAD

**Issue by cryptoquick** [arcjet/arcjet#38]
- [x] Rename owner to user
- [x] Remove `Hash` camelcase
- [x] Rename `recordHash` to `hash`
- [x] Refactor server find method to use streams
- [x] Refactor client methods to use streams
  - [x] `get`
  - [x] `set`
  - [x] `find`
- [x] Switch to entirely binary encoding #37 
- [x] Create Record accessors
- [x] Create Metadata enum

**Comment by cryptoquick** [comment]
Finished for 0.6.
